# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZeetHead < Formula
  desc "The Zeet CLI"
  homepage "https://zeet.co"
  version "0.4.1"

  head do
    url "https://github.com/zeet-dev/cli.git", :branch => "main"
    depends_on "go" => :build
  end

  def install
    if build.head?
        system "go", "build", *std_go_args
      end
    end
end
