# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZeetHead < Formula
  desc "The Zeet CLI"
  homepage "https://zeet.co"
  version "0.4.1"

  depends_on "go" => :build

  head do
    url "https://github.com/zeet-dev/cli.git", :branch => "main"
  end

  def install
    if build.head?
        ENV["GOPATH"] = buildpath

        bin_path = buildpath/"src/github.com/zeet-dev/cli"
        bin_path.install Dir["*"]
        cd bin_path do
          system "go", "build", "-o", bin/"zeet-head", "."
        end
      end
    end
end
