# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZeetRc < Formula
  desc "The Zeet CLI [w/ release candidates]"
  homepage "https://zeet.co"
  version "0.6.1-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zeet-dev/cli/releases/download/v0.6.1-rc1/zeet_0.6.1-rc1_darwin_x86_64.tar.gz"
      sha256 "47be2a83c3649c2926cfdca3fdf63b9bc3222036d60e7e13e6e4015cd421593e"

      def install
        bin.install "zeet" => "zeet-rc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zeet-dev/cli/releases/download/v0.6.1-rc1/zeet_0.6.1-rc1_darwin_arm64.tar.gz"
      sha256 "20642bb06c7da79c9a69dcd11db8e2a8cba84a868d6a83a87de4ddbf8f4a9c35"

      def install
        bin.install "zeet" => "zeet-rc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/zeet-dev/cli/releases/download/v0.6.1-rc1/zeet_0.6.1-rc1_linux_armv6.tar.gz"
      sha256 "7eb40789af9bbff4cc2bfe435fdbfcdd79f5b2056f207be8ac4a79436f5f51d6"

      def install
        bin.install "zeet" => "zeet-rc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zeet-dev/cli/releases/download/v0.6.1-rc1/zeet_0.6.1-rc1_linux_x86_64.tar.gz"
      sha256 "c5a5b8dbb187cab069237ee73972b1679248a7f5219357d6dbf884015e68a061"

      def install
        bin.install "zeet" => "zeet-rc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zeet-dev/cli/releases/download/v0.6.1-rc1/zeet_0.6.1-rc1_linux_arm64.tar.gz"
      sha256 "cb8fa89d0e53ed1229123634b8d283eb136414a50cc4308fe55eae612f500ae3"

      def install
        bin.install "zeet" => "zeet-rc"
      end
    end
  end
end
