# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZeetRc < Formula
  desc "The Zeet CLI [w/ release candidates]"
  homepage "https://zeet.co"
  version "0.5.0-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zeet-dev/cli/releases/download/v0.5.0-rc1/zeet_0.5.0-rc1_darwin_x86_64.tar.gz"
      sha256 "d94184187043bf3ce74480e6343f5e868fb10575157918ab50b53ac0d3bb73c1"

      def install
        bin.install "zeet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zeet-dev/cli/releases/download/v0.5.0-rc1/zeet_0.5.0-rc1_darwin_arm64.tar.gz"
      sha256 "e4abe1f9dd2218227f612445e1d85a51841cf6b40093ccd98da4b3e32d5a9d2a"

      def install
        bin.install "zeet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/zeet-dev/cli/releases/download/v0.5.0-rc1/zeet_0.5.0-rc1_linux_armv6.tar.gz"
      sha256 "16cda95bb8d0c6353383bc984bf221a1fc21e35d9a5ad9e608df01702928a01c"

      def install
        bin.install "zeet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zeet-dev/cli/releases/download/v0.5.0-rc1/zeet_0.5.0-rc1_linux_arm64.tar.gz"
      sha256 "bb72d184a1f53d090b262eedfc21025b49fb86885ddee269279054c4c88cf983"

      def install
        bin.install "zeet"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zeet-dev/cli/releases/download/v0.5.0-rc1/zeet_0.5.0-rc1_linux_x86_64.tar.gz"
      sha256 "6a3288c9a9082a738b5350acd5c43bebce42a0ac80c23cef66e44457369a48e3"

      def install
        bin.install "zeet"
      end
    end
  end
end
